[monte_carlo]
simulation = "Simulation.toml"
seed = 42

[[monte_carlo.chains]]
runs = 10
chain = ["dual_spiral"]

#[[monte_carlo.chains]]
#runs = 10
#chain = ["dual_raster"]

# so slow...
#[[monte_carlo.chains]]
#runs = 10
#chain = ["lissajous_scan"]

#[[monte_carlo.chains]]
#runs = 10
#chain = ["rosette_scan"]

# currently gravity, consider probabilistic bias instead?
#[[monte_carlo.chains]]
#runs = 10
#chain = ["center_rebias"]

# pretty good
#[[monte_carlo.chains]]
#runs = 10
#chain = ["concentric_shells"]

#[[monte_carlo.chains]]
#runs = 10
#chain = ["random_walk"]

#[[monte_carlo.chains]]
#runs = 10
#chain = ["random_curve"]

#[[monte_carlo.chains]]
#runs = 10
#chain = ["nested_spiral"]

[error]
distribution = "gaussian"
theta_mean = 0.0
theta_std = 0.02
phi_mean = 0.0
phi_std = 0.02

[strategy]
k = 10.0

[strategy.dual_spiral]
speed_a = 4.990651
speed_ratio = 1.883651

[strategy.dual_raster]
speed_a = 1.0
speed_ratio = 1.41421356

[strategy.lissajous_scan]
s1_wx = 1.5
s1_wy = 2.12132034
s1_delta = 0.0
s2_wx = 2.42705099
s2_wy = 3.43236842
s2_delta = 0.5

[strategy.rosette_scan]
s1_w1 = 1.0
s1_w2 = 1.41421356
s2_w1 = 1.4
s2_w2 = 1.61803399

[strategy.center_rebias]
velocity_a = 0.1
velocity_ratio = 1.41421356
drift_sigma = 20
max_turn_radius = 50
bias_strength = 1

[strategy.concentric_shells]
spiral_speed_a = 1.0
speed_ratio = 1.41421356

[strategy.random_walk]
step_duration_a = 1.0
step_duration_ratio = 1.41421356

[strategy.random_curve]
velocity_a = 0.1
velocity_ratio = 1.41421356
drift_sigma = 10
max_turn_radius = 50

[strategy.nested_spiral]
outer_radius = 0.05
inner_radius = 0.05
spiral_speed = 1.0
