[scenario]
name = "desmos_default"

[positions]
p1 = [0.0, 0.0, 0.0]
p2 = [0.0, 0.5, 10.5]
pt = [0, 0.0, 10]

[offsets]
theta_jumble = 0.0
phi_jumble = 0.0

[sda]
k = 10.0
alpha = 0.005 # from SIM config 
gamma = 0.5
beta = 0.5
omega_r = 10.0 #ideally pi_k / alpha
L_r = 0.15

[simulation]
q_max = 5.0
q_step = 0.01

[receiver]
dish_theta_offset = 0.52
dish_phi_offset = 0.36
body_radius = 0.5
dish_fov = 0.002
dish_slew_time = 0.3

[visualization]
enabled = false
cone_u_steps = 24
cone_v_steps = 32
spiral_trail_steps = 120
ribbon_v_steps = 8
