[satellite]
body_radius = 0.5
dish_fov = 2.0
max_beam_speed = 17.0 # physical limit 87, restricted due to camera  
max_fsm_speed = 1000.0 # !!not exact!!
max_fsm_radius = 1.0
beam_width = 0.5
k = 10.0

[simulation]
distance = 1000.0
t_step = 0.01
boresight_extension = 5.0
max_search_radius = 4.0
profile_replay = false
timeout = 100.0
enforce_speed_limit = true

[3d_viz]
cone_u_steps = 24
cone_v_steps = 32
spiral_trail_steps = 120
ribbon_v_steps = 8
profile_frames = false

[eye_viz]
axis_limit = 10.0
slider_debounce_ms = 1
hover_correlation_enabled = true
correlation_blob_alpha = 100

[mag_viz]
visual_limit_deg = 40.0
fov_cone_length = 1.01
beam_cone_length = 1.01
bottom_margin = 48.0
