[monte_carlo]
environment = "Environment.toml"
seed = 42
runs = 500
chain = ["lissajous_scan"]
error.distribution = "gaussian"
error.gaussian.std = 1.5

[strategy.dual_spiral]

[strategy.dual_raster]
speed_a = 4.013988
speed_ratio = 2.400
steps_a = 77
steps_b = 100

[strategy.lissajous_scan]
s1_wx = 15.526127
s1_wy = 14.249881
s1_delta = 2.957257
s2_wx = 16.992454
s2_wy = 3.821853
s2_delta = 5.530637

[strategy.rosette_scan]
s1_w1 = 6.949170
s1_w2 = 9.913765
s2_w1 = 7.542091
s2_w2 = 9.304704

[strategy.center_rebias]
velocity_a = 43.708
velocity_ratio = 2.316948
drift_sigma = 160.874
max_turn_radius = 863.263
bias_strength = 0.389001

[strategy.concentric_shells]

[strategy.random_walk]
step_duration_a = 1.0
step_duration_ratio = 1.41421356

[strategy.random_curve]
velocity_a = 100.0
velocity_ratio = 1.41421356
drift_sigma = 10000.0
max_turn_radius = 50000.0

[strategy.nested_spiral]
outer_radius = 50.0
inner_radius = 50.0
