[optimize]
strategy = "lissajous_scan"
method = "optuna"
trials = 100
trial_seed = 103

[monte_carlo]
environment = "Environment.toml"
seed = 42
runs = 500
error.distribution = "gaussian"
error.gaussian.std = 1.5