[scenario]
name = "default"
environment = "Environment.toml"
chain = ["minor_offset", "single_miss"]
visualize = "3d"

[s1]
bench_theta_offset = 1.0
bench_phi_offset = 1.0

[s2]
bench_theta_offset = -1.0
bench_phi_offset = 1.5

[strategy.minor_offset]
max_spiral_radius = "fov"

[strategy.single_miss]
a_spiral_radius = 3.0
b_spiral_radius = 3.0
